# -*- coding: utf-8 -*-
"""
Build FIRO_SPACEConfig.csv from the rule curves of a daily ResSim run.

For each reservoir the FIRO_SPACE target is the rule curve plus a fraction of
the flood space above it:

    FIRO = Rule Curve + FLOOD_SPACE_FRACTION * (max con - Rule Curve)

max con is the top of that reservoir's rule curve (full pool). So in winter,
with the rule curve at min con, FIRO sits FLOOD_SPACE_FRACTION of the
conservation band above it, and it meets the rule curve when the pool is full.

The rule curves come from the "<reservoir>-Rule Curve Elev-ZONE" columns of a
model_check extract (reservoirs.csv) of a DAILY run. Leap years are skipped:
ResSim shifts the curve a day after 29 Feb in them, so they do not match a
generic-year Month/Day table.

Desktop Python 3 with pandas. Usage:

    python build_FIRO_SPACEConfig.py <run folder>

<run folder> is a model_check output folder of a daily run, e.g.
data/Check/Flood_64_Temp1Day_2026-09-28. Writes FIRO_SPACEConfig.csv next to
FIRO_SPACE.py, keeping the reservoir columns and their order from the file
already there.
"""

import os
import sys

import pandas as pd

################################################################################
# USER INPUT

# Share of the flood space (max con minus rule curve) FIRO may hold above the
# rule curve. 0.10 = 10%.
FLOOD_SPACE_FRACTION = 0.10

DECIMALS = 2

################################################################################

HERE = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.join(os.path.dirname(HERE), "FIRO_SPACEConfig.csv")
ZONE_SUFFIX = "-Rule Curve Elev-ZONE"


def existingColumns():
    """Reservoir columns of the current config, in order, or [] if none."""
    if not os.path.exists(OUTPUT):
        return []
    with open(OUTPUT, encoding="utf-8") as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            cols = [c.strip() for c in line.strip().split(",")]
            return [c for c in cols[2:] if c]
    return []


def ruleCurves(runFolder):
    """{reservoir: Series indexed by (month, day)} for a generic non-leap year."""
    df = pd.read_csv(os.path.join(runFolder, "reservoirs.csv"),
                     index_col=0, parse_dates=True)
    df = df[~df.index.is_leap_year]
    days = pd.date_range("2001-01-01", "2001-12-31", freq="D")
    keys = pd.MultiIndex.from_arrays([days.month, days.day])
    curves = {}
    for col in df.columns:
        if not col.endswith(ZONE_SUFFIX):
            continue
        resv = col[:-len(ZONE_SUFFIX)]
        s = df[col].dropna()
        byDay = s.groupby([s.index.month, s.index.day])
        spread = byDay.max() - byDay.min()
        if (spread > 0.005).any():
            raise SystemExit(
                "%s rule curve differs between years on %d days, so it is not "
                "a generic-year curve." % (resv, int((spread > 0.005).sum())))
        curve = byDay.first().reindex(keys)
        if curve.isna().any():
            raise SystemExit(
                "The run does not cover every date of a non-leap year for %s "
                "(first missing: %s). Use a daily run that does."
                % (resv, curve[curve.isna()].index[0]))
        curves[resv] = curve
    return curves


def build(curves, names):
    table = pd.DataFrame({"Month": curves[names[0]].index.get_level_values(0),
                          "Day": curves[names[0]].index.get_level_values(1)})
    for resv in names:
        rc = curves[resv].values
        maxCon = rc.max()
        table[resv] = (rc + FLOOD_SPACE_FRACTION * (maxCon - rc)).round(DECIMALS)
    return table


def check(table, curves, names):
    """FIRO never below the rule curve, never above max con, 365 days."""
    assert len(table) == 365, len(table)
    tol = 0.5 * 10 ** -DECIMALS + 1e-9
    for resv in names:
        rc = curves[resv].values
        firo = table[resv].values
        assert (firo >= rc - tol).all(), resv
        assert (firo <= rc.max() + tol).all(), resv


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    runFolder = sys.argv[1]
    curves = ruleCurves(runFolder)
    if not curves:
        raise SystemExit("No '*%s' columns in %s" % (ZONE_SUFFIX, runFolder))
    names = existingColumns() or sorted(curves)
    missing = [n for n in names if n not in curves]
    if missing:
        raise SystemExit("No rule curve in %s for: %s"
                         % (runFolder, ", ".join(missing)))
    table = build(curves, names)
    check(table, curves, names)

    pct = int(round(FLOOD_SPACE_FRACTION * 100))
    header = [
        "# FIRO_SPACE rule curve. One row per day of a generic (non-leap) year.",
        "# Read by scripts/externalRules/FIRO_SPACE.py",
        "#",
        "# GENERATED by externalRules/_offline_tests/build_FIRO_SPACEConfig.py",
        "# from the rule curves of %s." % os.path.basename(os.path.normpath(runFolder)),
        "# Rerun the generator rather than editing by hand.",
        "#",
        "#   FIRO = Rule Curve + %d%% x (max con - Rule Curve)" % pct,
        "#",
        "# max con is the top of each reservoir's rule curve. In winter FIRO sits",
        "# %d%% of the conservation band above the rule curve, and it meets the" % pct,
        "# rule curve when the pool is full.",
        "#",
        "# A BLANK cell means NO TARGET that day: the rule stands down and the rest",
        "# of the rule stack operates the project. A project with no column here is",
        "# never controlled. Column headers are matched to ResSim reservoir names",
        "# ignoring surrounding spaces and capitalization.",
    ]
    # newline="" keeps Windows from writing blank lines between rows
    with open(OUTPUT, "w", encoding="utf-8", newline="") as f:
        f.write("\n".join(header) + "\n")
        table.to_csv(f, index=False, lineterminator="\n",
                     float_format="%." + str(DECIMALS) + "f")
    print("Wrote %d days x %d reservoirs to %s" % (len(table), len(names), OUTPUT))


if __name__ == "__main__":
    main()
